### ISSUE TITLE
Open source ML alternative

### ISSUE THREAD

**Issue by osanseviero** [AlexandreSajus/JARVIS#1]
Hi there!

This project is very cool! I wonder if you've experimented with open-access models. 

E.g. you could combine Whisper (for speech to text), Mistral or Llama (for text generation) and Coqui or Bark (for text to speech). Tools such as https://github.com/Vaibhavs10/insanely-fast-whisper or transformers can help here.

**Comment by AlexandreSajus** [comment]
I have not experimented with this myself, but someone referred me to this local open-access version of a vocal assistant:
https://github.com/KoljaB/LocalAIVoiceChat
