### ISSUE TITLE
How to avoid sending silence wav audiosl?

### ISSUE THREAD

**Issue by twmht** [AlexandreSajus/JARVIS#10]
I've noticed that even when no one is speaking, WAV files continue to be sent to the Speech to Text API, resulting in the generation of self-generated transcripts. How can this be avoided?

**Comment by AlexandreSajus** [comment]
You'll have to code this within `main.py`

In line 91:
```python
    while True:
        # Record audio
        log("Listening...")
        speech_to_text()
        log("Done listening")

        # Transcribe audio
        current_time = time()
        loop = asyncio.new_event_loop()
        asyncio.set_event_loop(loop)
        words = loop.run_until_complete(transcribe(RECORDING_PATH))
```

After `log("Done listening")`, you need to load the .wav audio file recorded at RECORDING_PATH. Check the max volume. If max_volume is under a constant value (silence), pass
