### ISSUE TITLE
Module not found: rhasspysilence

### ISSUE THREAD

**Issue by AlexandreSajus** [AlexandreSajus/JARVIS#4]

**Comment by AlexandreSajus** [comment]
![image](https://github.com/AlexandreSajus/JARVIS/assets/69819558/270a3613-5cf9-4a8b-9181-90348765214d)

**Comment by AlexandreSajus** [comment]
Try `pip install rhasspysilence` in a terminal

**Comment by mayurmakwanaais** [comment]
![image](https://github.com/AlexandreSajus/JARVIS/assets/69819558/7ca361eb-5a02-4b0e-9cd1-1c4a09d1c6a8)

**Comment by mayurmakwanaais** [comment]
when i run display.py
![image](https://github.com/AlexandreSajus/JARVIS/assets/69819558/73265d22-60cf-4798-b23e-c3c7bc773a98)

**Comment by AlexandreSajus** [comment]
There seem to be issues with your Python environment. Could you try again but with a clean Python environment? You can find a tutorial on how to create new Python environments here:
https://packaging.python.org/en/latest/guides/installing-using-pip-and-virtual-environments/

**Comment by mayurmakwanaais** [comment]
![image](https://github.com/AlexandreSajus/JARVIS/assets/69819558/93f5d610-b74d-4b6c-97f9-9f27e181a9e2)

**Comment by mayurmakwanaais** [comment]
as per you told i created envirement but still package not installing

**Comment by AlexandreSajus** [comment]
Ah my bad, the correct command is `pip install rhasspy-silence`

You can also install all requirements for this project with `pip install -r requirements.txt`

**Comment by AlexandreSajus** [comment]
Closing this as there is no response. Feel free to reopen if it still does not work
